default_platform(:mac)

api_key = app_store_connect_api_key(
  key_id: ENV["APPLE_APPSTORE_CONNECT_API_KEY_ID"],
  issuer_id: ENV["APPLE_APPSTORE_CONNECT_API_ISSUER_ID"],
  key_content: ENV["APPLE_APPSTORE_CONNECT_API_KEY"],
  is_key_content_base64: true,
  duration: 500, # maximum 1200
)

platform :mac do
  desc "Build and upload a new version to the App Store"
  lane :deploy_mac do

    # Important to run in CI
    setup_ci(
    )

    # Setup certificates using match
    match(
        type: "appstore",
        app_identifier: "com.edamametechnologies.edamame",
        readonly: true,
        verbose: true,
        # Need to specify additional_cert_types for macOS
        additional_cert_types: ["mac_installer_distribution"]
    )
    
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      destination: "generic/platform=macOS",
      export_method: "app-store",
      verbose: true
    )

    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end

end


platform :mac do
  desc "Setup certs and profiles for macOS testing"
  lane :test_mac do

    # Important to run in CI
    setup_ci(
    )

    # Register the CI Runner Machine
    runner_udid = `system_profiler SPHardwareDataType | grep 'Provisioning UDID' |  awk '{print $3}'`.strip
    register_device(
      udid: runner_udid,
      name: "CI Runner Machine"
    )

    # Setup certificates using match for local testing
    match(
        type: "development",
        app_identifier: "com.edamametechnologies.edamame",
        readonly: false,
        # Need to update the profile for the new device (the Runner in this case)
        force_for_new_devices: true,
        force: true,
        verbose: true
    )

  end

  platform :mac do
    desc "Setup certs and profiles for macOS development"
    lane :dev_mac do

      # Setup certificates using match for local testing
      match(
          type: "development",
          app_identifier: "com.edamametechnologies.edamame",
          readonly: false,
          # Need to update the profile for the new device (the Runner in this case)
          force_for_new_devices: true,
          force: true,
          verbose: true
      )

      match(
          type: "appstore",
          app_identifier: "com.edamametechnologies.edamame",
          readonly: true,
          verbose: true,
          # Need to specify additional_cert_types for macOS
          additional_cert_types: ["mac_installer_distribution"]
      )

    end

  end

end
