#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
    configure)
        # Remind about configuration
        echo "Please configure /etc/edamame_posture.conf and restart the service"
        
        # Enable and start the service
        systemctl daemon-reload
        systemctl enable edamame_posture.service
        systemctl start edamame_posture.service
        ;;
esac

exit 0