#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
    remove|upgrade|deconfigure)
        if command -v systemctl >/dev/null 2>&1; then
            systemctl stop edamame_posture.service || true
            systemctl disable edamame_posture.service || true
            systemctl daemon-reload
        fi
        ;;
esac

exit 0