name: Build and publish for Linux Alpine Aarch64

on:
  workflow_dispatch:

# Auto cancel previous runs if they were not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    env:
      EDAMAME_APP_SENTRY: ${{ secrets.EDAMAME_APP_SENTRY }}
      PWNED_API_KEY: ${{ secrets.PWNED_API_KEY }}
      EDAMAME_TARGET: ${{ secrets.EDAMAME_TARGET }}
      EDAMAME_CA_PEM: ${{ secrets.EDAMAME_CA_PEM }}
      EDAMAME_CLIENT_PEM: ${{ secrets.EDAMAME_CLIENT_PEM }}
      EDAMAME_CLIENT_KEY: ${{ secrets.EDAMAME_CLIENT_KEY }}
      LAMBDA_SIGNATURE: ${{ secrets.LAMBDA_SIGNATURE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu musl-tools pkg-config libssl-dev
          rustup target add aarch64-unknown-linux-musl

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Configure Git Authentication to import private crates
        run: |
          git config --global user.email "dev@edamame.tech"
          git config --global user.name "EDAMAME Dev"
          git config --global url."https://edamamedev:${{ secrets.DEV_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Build application
        env:
          CC_aarch64_unknown_linux_musl: aarch64-linux-gnu-gcc
          OPENSSL_DIR: /usr
          OPENSSL_STATIC: "1"
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-gnu-gcc
          RUSTFLAGS: "-C target-feature=-crt-static"
        run: |
          cargo build --release --target aarch64-unknown-linux-musl

      # Dev only (upload to dev folder)
      - name: Upload posture to AWS
        if: github.ref == 'refs/heads/dev'
        shell: bash
        run: |
          VERSION=$(grep '^version =' ./Cargo.toml | awk '{print $3}' | tr -d '"')
          aws s3 cp ./target/aarch64-unknown-linux-musl/release/edamame_posture \
            s3://edamame-posture/dev/linux_alpine/${VERSION}/edamame_posture --acl public-read

      # Main only (upload to base folder)
      - name: Upload posture to AWS
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          VERSION=$(grep '^version =' ./Cargo.toml | awk '{print $3}' | tr -d '"')
          aws s3 cp ./target/aarch64-unknown-linux-musl/release/edamame_posture \
            s3://edamame-posture/linux_alpine/${VERSION}/edamame_posture --acl public-read
          aws s3 cp ./target/aarch64-unknown-linux-musl/release/edamame_posture \
            s3://edamame-posture/linux_alpine/latest/edamame_posture --acl public-read

      - name: Dump EDAMAME Posture sessions
        uses: edamametechnologies/edamame_posture_action@v0
        with:
          dump_sessions_log: true
