name: Test Windows with pcap

on:
  workflow_dispatch:

# Auto cancel previous runs if they were not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Install pcap
        shell: bash
        run: |
          choco install wget
          choco install autohotkey.portable
          wget https://nmap.org/npcap/dist/npcap-1.80.exe
          autohotkey ./windows/npcap.ahk ../npcap-1.80.exe
          sleep 20
          ls -la /c/Windows/System32/Npcap    

